API_key: '114eeff82a1f6c329ac960107187e344'
connection_url: 'mongodb://pigpig:0iEF&C84k4gqe&d&2D38%5EtNb&xln6d03hXLOGAcbY0LeRGUlGj@192.168.100.10:27017/'
db_ecoterra: 'Ecoterra'
weather_collection: 'weather'

cities:
  Atlixco: 
  - 18.923085025419557
  - -98.39557636380162
  Cuapiaxtla: 
  - 19.295867896783285
  - -97.76888973800806
  Tehuacan: 
  - 18.52639736316348
  - -97.47871399384229
  Phoenix:
  - 33.39119277195364
  - -112.5928040604769

notifications:
  'temp_min': 22.18
  'temp_max': 22.18
  'pressure_min': 1017
  'pressure_max': 1040
  'humidity_min': 12
  'humidity_max': 16
  'AirPollution':
    'so2': 
      'Good': 
        'min': 0
        'max': 20
      'Fair': 
        'min': 20
        'max': 80
      'Moderate':
        'min': 80
        'max': 250
      'Poor':
        'min': 250
        'max': 350
      'Very Poor':
        'min': 350
    'no2':
      'Good': 
        'min': 0
        'max': 40
      'Fair': 
        'min': 40
        'max': 70
      'Moderate':
        'min': 70
        'max': 150
      'Poor':
        'min': 150
        'max': 200
      'Very Poor':
        'min': 200
    'pm10':
      'Good': 
        'min': 0
        'max': 20
      'Fair': 
        'min': 20
        'max': 50
      'Moderate':
        'min': 50
        'max': 100
      'Poor':
        'min': 100
        'max': 200
      'Very Poor':
        'min': 200
    'pm2_5':
      'Good': 
        'min': 0
        'max': 10
      'Fair': 
        'min': 10
        'max': 25
      'Moderate':
        'min': 25
        'max': 50
      'Poor':
        'min': 50
        'max': 75
      'Very Poor':
        'min': 75
    'o3':
      'Good': 
        'min': 0
        'max': 60
      'Fair': 
        'min': 60
        'max': 100
      'Moderate':
        'min': 100
        'max': 140
      'Poor':
        'min': 140
        'max': 180
      'Very Poor':
        'min': 180
    'co':
        'Good': 
          'min': 0
          'max': 4400
        'Fair': 
          'min': 4400
          'max': 9400
        'Moderate':
          'min': 9400
          'max': 12400
        'Poor':
          'min': 12400
          'max': 15400
        'Very Poor':
          'min': 15400
      